### PR TITLE
Add datadog-logging to zuul and nodepool

### PR DESCRIPTION
**Pull request by jamielennox**
Add the datadog-logging module to zuul and nodepool to send error
messages to datadog.

Signed-off-by: Jamie Lennox <jamielennox@gmail.com>

### CODE REVIEW

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/162/1487278090.43/bonnyci-run-check-multinode : POST_FAILURE in 10s

**Comment by jamielennox** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/162/1487282264.32/bonnyci-run-check-multinode : FAILURE in 5m 47s

**Review by omgjlk — APPROVED** [review]
LGTM

**Pull request merged**
