### PR TITLE
Upload to better log url

### PR DESCRIPTION
**Pull request by jamielennox**
Construct a better log path for results that we can expose to users.

### CODE REVIEW

**Review by omgjlk — DISMISSED** [review]

**Comment by omgjlk** [comment]
You forgot a signed-off-by.

**Review by ConsoleCatzirl — APPROVED** [review]
Nice, lgtm

**Review by omgjlk — APPROVED** [review]

**Comment by anne-bonny** [comment]
Starting gate_github jobs.

**Comment by anne-bonny** [comment]
Starting gate_github jobs.

**Pull request merged**
