### PR TITLE
[DNM] Reproducing signed-off-by issues.

### PR DESCRIPTION
**Pull request by eggshell**

### CODE REVIEW

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by gandelman-a** [comment]
recheck

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/141/1487019946.27/bonnyci-run-check-multinode : NOT_REGISTERED

**Comment by eggshell** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/141/1487020178.75/bonnyci-run-check-multinode : NOT_REGISTERED

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/141/1487020519.67/bonnyci-run-check-multinode : NOT_REGISTERED

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/141/1487020603.79/bonnyci-run-check-multinode : NOT_REGISTERED

**Comment by gandelman-a** [comment]
recheck

**Comment by gandelman-a** [comment]
recheck

**Comment by gandelman-a** [comment]
recheck

**Comment by gandelman-a** [comment]
recheck

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/141/1487023872.45/bonnyci-run-check-multinode : NOT_REGISTERED

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/141/1487024024.19/bonnyci-run-check-multinode : FAILURE in 53s

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/141/1487024929.74/bonnyci-run-check-multinode : FAILURE in 53s

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/141/1487025468.48/bonnyci-run-check-multinode : FAILURE in 53s

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/141/1487025596.72/bonnyci-run-check-multinode : FAILURE in 53s

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/141/1487025749.4/bonnyci-run-check-multinode : FAILURE in 53s

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/141/1487026141.61/bonnyci-run-check-multinode : FAILURE in 4m 57s

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/141/1487035889.45/bonnyci-run-check-multinode : FAILURE in 4m 59s

**Comment by omgjlk** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/141/1487052332.46/bonnyci-run-check-multinode : FAILURE in 5m 19s

**Pull request closed without merging**
