### PR TITLE
Fix multinode label assignment for BonnyCI jobs, clean noop tests

### PR DESCRIPTION
**Pull request by gandelman-a**
This explicitly defines node labels for the bonnyci-run-* jobs instead
of using job templating, which apparently does not work as I thought.

Also, this jobs the test stubs that we needed to put in place to get
the first commit through the gate, and it drops unused job config.

Signed-off-by: Adam Gandelman <adamg@ubuntu.com>

### CODE REVIEW

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/142/1487026630.1/bonnyci-run-check-multinode : FAILURE in 54s

**Review by jamielennox — APPROVED** [review]

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/142/1487027062.71/bonnyci-run-check-multinode : FAILURE in 18s

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/142/1487027357.63/bonnyci-run-check-multinode : FAILURE in 53s

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/142/1487027644.37/bonnyci-run-check-multinode : FAILURE in 53s

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/142/1487031011.0/bonnyci-run-gate-multinode : FAILURE in 55s

**Comment by jamielennox** [comment]
gate-recheck

**Pull request merged**
