### PR TITLE
Change the default kibana ServerAlias to 'kibana'

### PR DESCRIPTION
**Pull request by ConsoleCatzirl**
You can't use default(omit) in group_vars

Signed-off-by: K Jonathan Harker <Jonathan.Harker@ibm.com>

### CODE REVIEW

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/299/1491413866.58/bonnyci-run-check-multinode : POST_FAILURE in 15s

**Review by omgjlk — APPROVED** [review]

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/299/1491414348.6/bonnyci-run-check-multinode : POST_FAILURE in 23s

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/299/1491414596.29/bonnyci-run-check-multinode : POST_FAILURE in 15s

**Comment by ConsoleCatzirl** [comment]
recheck

**Pull request merged**
