### PR TITLE
[2 of 2] Add another subnode to the multinode label

### PR DESCRIPTION
**Pull request by ConsoleCatzirl**
After the subnode count has increased, add the new subnode to our
dynamic inventory script for the multinode test.

Depends-On: BonnyCI/hoist#83
Signed-off-by: K Jonathan Harker <Jonathan.Harker@ibm.com>

### CODE REVIEW

**Review by omgjlk — APPROVED** [review]

**Comment by anne-bonny** [comment]
Starting gate_github jobs.

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/84/1486074697.71/ubuntu-hoist : FAILURE in 53s

**Comment by omgjlk** [comment]
gate-recheck

**Comment by anne-bonny** [comment]
Starting gate_github jobs.

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/84/1486078315.76/ubuntu-hoist : FAILURE in 3m 55s

**Comment by ConsoleCatzirl** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/84/1486090758.59/ubuntu-hoist : FAILURE in 3m 55s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/84/1486090758.59/ansible-syntax : SUCCESS in 55s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/84/1486090758.59/hoist-checks : SUCCESS in 23s

**Comment by ConsoleCatzirl** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/84/1486157393.0/ubuntu-hoist : FAILURE in 4m 11s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/84/1486157393.0/ansible-syntax : SUCCESS in 55s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/84/1486157393.0/hoist-checks : SUCCESS in 22s

**Comment by ConsoleCatzirl** [comment]
recheck

**Comment by ConsoleCatzirl** [comment]
recheck

**Comment by ConsoleCatzirl** [comment]
recheck

**Comment by ConsoleCatzirl** [comment]
recheck

**Pull request merged**
