### PR TITLE
Specify sandbox-v3 project

### PR DESCRIPTION
**Pull request by jamielennox**
We probably could have reused the BonnyCI/sandbox for this, but we need
to specify the sandbox-v3 project to get it to pick up events.

Signed-off-by: Jamie Lennox <jamielennox@gmail.com>

### CODE REVIEW

**Comment by omgjlk** [comment]
recheck

**Review by omgjlk — APPROVED** [review]

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/291/1491338409.04/bonnyci-run-check-multinode : FAILURE in 7m 40s

**Comment by jamielennox** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/291/1491347081.29/bonnyci-run-check-multinode : POST_FAILURE in 17s

**Comment by jamielennox** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/291/1491348805.43/bonnyci-run-check-multinode : POST_FAILURE in 15s

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/gate_github/BonnyCI/hoist/291/1491349475.51/bonnyci-run-gate-multinode : POST_FAILURE in 18s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/gate_github/BonnyCI/hoist/291/1491349506.08/bonnyci-run-gate-multinode : POST_FAILURE in 16s

**Pull request merged**
