### PR TITLE
Add playbook requirements to the ansible-runner venv

### PR DESCRIPTION
**Pull request by ConsoleCatzirl**
Also use the ansible-runner venv when deploying in vagrant.

Signed-off-by: K Jonathan Harker <Jonathan.Harker@ibm.com>

### CODE REVIEW

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/214/1489177415.38/bonnyci-run-check-multinode : FAILURE in 7m 40s

**Comment by gandelman-a** [comment]
recheck

**Review by gandelman-a — APPROVED** [review]

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/214/1489183422.28/bonnyci-run-gate-multinode : FAILURE in 6m 57s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/214/1489184452.88/bonnyci-run-gate-multinode : FAILURE in 7m 01s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/214/1489185165.88/bonnyci-run-gate-multinode : FAILURE in 6m 59s

**Pull request merged**
