### PR TITLE
Remove no-longer-used inventory files

### PR DESCRIPTION
**Pull request by ConsoleCatzirl**
Signed-off-by: K Jonathan Harker <Jonathan.Harker@ibm.com>

### CODE REVIEW

**Review by jamielennox — APPROVED** [review]

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/207/1489102173.01/bonnyci-run-gate-multinode : FAILURE in 2h 05m 10s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/207/1489109744.52/bonnyci-run-gate-multinode : FAILURE in 56s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/207/1489109809.9/bonnyci-run-gate-multinode : FAILURE in 1m 05s

**Comment by jamielennox** [comment]
recheck

**Pull request merged**
