### PR TITLE
Rename no-docker tag to not-on-docker

### PR DESCRIPTION
**Pull request by ConsoleCatzirl**
This makes a little more sense.

Signed-off-by: K Jonathan Harker <Jonathan.Harker@ibm.com>

### CODE REVIEW

**Review by omgjlk — APPROVED** [review]
This will probably fail gate, as there is a conflicting change already in the pipeline.

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/143/1487122925.0/bonnyci-run-check-multinode : FAILURE in 7m 04s

**Comment by ConsoleCatzirl** [comment]
recheck

**Pull request merged**
