### PR TITLE
Check for existing letsencrypt cert before trying to back it up

### PR DESCRIPTION
**Pull request by gandelman-a**
Related-Issue: BonnyCI/projman#151

Signed-off-by: Adam Gandelman <adamg@ubuntu.com>

### CODE REVIEW

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/220/1489433838.52/bonnyci-run-check-multinode : RETRY_LIMIT

**Comment by gandelman-a** [comment]
recheck

**Review by eggshell — COMMENTED** [review]
lgtm.

**Review by omgjlk — APPROVED** [review]

**Review by ConsoleCatzirl — APPROVED** [review]

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/220/1489434878.54/bonnyci-run-check-multinode : FAILURE in 48s

**Comment by gandelman-a** [comment]
recheck

**Pull request merged**
