### PR TITLE
Redesign gate pipeline layout

### PR DESCRIPTION
**Pull request by omgjlk**
Trigger on our check status or a positive review, or a gate-recheck
comment.
Require a positive review from somebody with write access, and our check
status.
Reject on a negative review from somebody with write access.

Do not comment on gate start.
Do not trigger/remove labels.

Based on design from
https://github.com/BonnyCI/lore/blob/master/developers/contributing/designs/github-pr-check-gate.md

Signed-off-by: Jesse Keating <jkeating@j2solutions.net>

### CODE REVIEW

**Comment by omgjlk** [comment]
Do not merge until zuul has been restarted to handle these triggers/requirements.

**Review by rattboi — APPROVED** [review]
LGTM

**Comment by rattboi** [comment]
gate-recheck

**Comment by anne-bonny** [comment]
Starting gate_github jobs.

**Review by gandelman-a — APPROVED** [review]

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/101/1486166370.47/ubuntu-hoist : FAILURE in 2m 51s

**Comment by omgjlk** [comment]
gate-recheck

**Comment by anne-bonny** [comment]
Starting gate_github jobs.

**Pull request merged**
