### PR TITLE
Remove github.ibm.com references

### PR DESCRIPTION
**Pull request by omgjlk**
We're no longer hosted there, so remove the setup that was used to be
able to reach there.

Signed-off-by: Jesse Keating <jkeating@j2solutions.net>

### CODE REVIEW

**Comment by omgjlk** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- echo-true : NOT_REGISTERED

**Comment by omgjlk** [comment]
recheck

**Comment by omgjlk** [comment]
recheck

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by omgjlk** [comment]
recheck

**Review by jamielennox — APPROVED** [review]

**Comment by anne-bonny** [comment]
Starting gate_github jobs.

**Comment by anne-bonny** [comment]
Starting gate_github jobs.

**Pull request merged**
