### PR TITLE
Add new ssh key for jamie

### PR DESCRIPTION
**Pull request by jamielennox**
Yes, this is a brand new key and not just me re-adding the old one.

Signed-off-by: Jamie Lennox <jamielennox@gmail.com>

### CODE REVIEW

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/272/1490647540.5/bonnyci-run-check-multinode : FAILURE in 1m 14s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/272/1490647805.32/bonnyci-run-check-multinode : FAILURE in 1m 13s

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/272/1490648271.03/bonnyci-run-check-multinode : FAILURE in 1m 12s

**Review by gandelman-a — APPROVED** [review]

**Pull request merged**
