### PR TITLE
Add vhost for Kibana

### PR DESCRIPTION
**Pull request by ConsoleCatzirl**
Add a reverse-proxy vhost for Kibana.

Signed-off-by: K Jonathan Harker <Jonathan.Harker@ibm.com>

### CODE REVIEW

**Comment by ConsoleCatzirl** [comment]
I have not yet created a DNS entry for system-logs.bonnyci.portbleu.com, feel free to bikeshed on the name.

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/152/1487122701.42/bonnyci-run-check-multinode : FAILURE in 1m 48s

**Comment by ConsoleCatzirl** [comment]
recheck

**Review by omgjlk — COMMENTED** [review]
This all looks okay, but we should probably wait until we migrate to the new cloud to turn this on. Just commenting for now.

**Comment by missaugustina** [comment]
Looks like this is part of BonnyCI/projman#126

**Comment by ConsoleCatzirl** [comment]
I agree, this can wait until we migrate to the new cloud.

**Comment by ConsoleCatzirl** [comment]
We're now ready for this in our new cloud

**Review by gandelman-a — APPROVED** [review]

**Pull request merged**
