### PR TITLE
Lore merged with bonnyci.org

### LINKED ISSUE #124: Merge lore and bonnyci.org

### PR DESCRIPTION
**Pull request by SpamapS**
All lore is now on the website.

Closes #124

### CODE REVIEW

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/125/1486579489.65/ubuntu-hoist : FAILURE in 7m 42s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/125/1486579489.65/ansible-syntax : SUCCESS in 57s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/125/1486579489.65/hoist-checks : FAILURE in 19s

**Review by eggshell — APPROVED** [review]
lgtm

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/125/1486582188.52/ubuntu-hoist : FAILURE in 6m 08s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/125/1486582569.65/ubuntu-hoist : FAILURE in 5m 50s

**Pull request merged**
