### PR TITLE
Fix 'recheck' regexes to be more strict

### LINKED ISSUE #101: `gate_recheck` comment triggers the check pipeline.
We have a config of

```
    trigger:
      github:
        - event:
            - pr-open
            - pr-change
            - pr-reopen
        - event: pr-comment
          comment: (?i)recheck
```

on `check_github`. But in https://github.com/BonnyCI/hoist/pull/87#issuecomment-276810154 I issued a comment of `gate_recheck` and it triggered the `check_github` pipeline instead. Our regex needs work.

### PR DESCRIPTION
**Pull request by rattboi**
Currently, pr-comment can be triggered by any comment containing our
recheck term. This fixes the regex so that you must only have the term
'recheck', or the term 'gate-recheck' in your comment.

Fixes BonnyCI/projman#101

Signed-off-by: Bradon Kanyid <rattboi@gmail.com>

### CODE REVIEW

**Comment by rattboi** [comment]
Fixes hoist/projman#101

**Review by mlangbehn — APPROVED** [review]
Looks good to me. Nice catch.

**Review by ConsoleCatzirl — APPROVED** [review]

**Comment by rattboi** [comment]
gate-recheck

**Comment by anne-bonny** [comment]
Starting gate_github jobs.

**Pull request merged**
