### PR TITLE
[DNM] Testing DPKG in Bonny [DMN]

### PR DESCRIPTION
**Pull request by mlangbehn**
Signed-off-by: Matt Langbehn <matthew.langbehn@gmail.com>

### CODE REVIEW

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/334/1492015717.9/bonnyci-run-check-multinode : FAILURE in 12s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/334/1492016838.43/bonnyci-run-check-multinode : FAILURE in 12s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/334/1492017093.83/bonnyci-run-check-multinode : FAILURE in 12s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/334/1492017196.69/bonnyci-run-check-multinode : FAILURE in 13s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/334/1492017321.24/bonnyci-run-check-multinode : FAILURE in 16s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/334/1492017391.08/bonnyci-run-check-multinode : FAILURE in 3m 52s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/334/1492017918.52/bonnyci-run-check-multinode : FAILURE in 3m 47s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/334/1492018535.02/bonnyci-run-check-multinode : FAILURE in 4m 48s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/334/1492019345.11/bonnyci-run-check-multinode : FAILURE in 3m 50s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/334/1492019754.14/bonnyci-run-check-multinode : FAILURE in 3m 49s

**Comment by ConsoleCatzirl** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/334/1492021626.06/bonnyci-run-check-multinode : FAILURE in 4m 35s

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/334/1492024379.02/bonnyci-run-check-multinode : FAILURE in 4m 28s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/334/1492028601.37/bonnyci-run-check-multinode : FAILURE in 4m 25s

**Pull request closed without merging**
