### PR TITLE
Force an SSH re-key for all bastion users who need it

### PR DESCRIPTION
**Pull request by gandelman-a**
This re-keys my bastion account and removes all others.  If you need
SSH access to our systems, you can submit a PR re-adding yourself
with a new SSH key.

It also updates the removal task to actually remove the old users
home directories.

Signed-off-by: Adam Gandelman <adamg@ubuntu.com>

### CODE REVIEW

**Review by loafyloaf — DISMISSED** [review]

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/262/1490293171.51/bonnyci-run-check-multinode : FAILURE in 7m 47s

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/262/1490295390.44/bonnyci-run-check-multinode : FAILURE in 8m 42s

**Comment by gandelman-a** [comment]
recheck

**Review by mlangbehn — COMMENTED** [review]
Looks good to me.

**Comment by gandelman-a** [comment]
Going to block this actually. Looks like I may not be online on Friday and do not want to lock everyone out, in case something goes down.

**Review by ConsoleCatzirl — APPROVED** [review]

**Pull request merged**
