### PR TITLE
Add check for unused jobs

### PR DESCRIPTION
**Pull request by mlangbehn**
Previously, there was no test for jobs in roles/zuul/files/jobs/ that
were not being used. Now, tests/check-unused-jobs.sh warns if any unused
jobs are found.

Signed-off-by: Matt Langbehn <matthew.langbehn@gmail.com>

### CODE REVIEW

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/hoist/235/1489606092.29/bonnyci-run-check-multinode : FAILURE in 8m 06s

**Comment by mlangbehn** [comment]
recheck

**Review by eggshell — COMMENTED** [review]
lgtm, but I'll let others review.

**Review by jasontclark — COMMENTED** [review]
LGTM.

**Review by ConsoleCatzirl — APPROVED** [review]

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/gate_github/BonnyCI/hoist/235/1489614177.8/bonnyci-run-gate-multinode : FAILURE in 7m 39s

**Pull request merged**
