### PR TITLE
Seperate nodepool and bonny setup role

### PR DESCRIPTION
**Pull request by jamielennox**
There are standard requirements to using a node as a nodepool element.
Seperate this out into the basic nodepool element that can be submitted
upstream and reused in infra.

### CODE REVIEW

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/43/1483701507.92/ubuntu-hoist : FAILURE in 54s

**Comment by omgjlk** [comment]
Missing signed off by.

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/43/1483938142.11/ubuntu-hoist : FAILURE in 59s

**Review by omgjlk — APPROVED** [review]
This looks good to me, passes Travis.

**Comment by anne-bonny** [comment]
Starting gate_github jobs.

**Pull request merged**
