### PR TITLE
Fix first-time inventory hosts from cron

### LINKED ISSUE #38: First-time setup of inventory hosts from bastion cron causes failure (known_hosts)
When ansible attempts to connect for the first time to a host in the inventory on a new bastion, the known_hosts file is missing entries for these hosts, and attempts to interactively ask if you're ok with the host key.

Since this is from cron, the interactive aspect fails, and so the hosts are never properly registered.

Note that this is default behavior in ansible.

More info here: http://docs.ansible.com/ansible/intro_getting_started.html#host-key-checking

### PR DESCRIPTION
**Pull request by rattboi**
Fixes #38

I'm not positive about the security implications of this change, so if
this makes no sense, just dump it. Not sure how else we'd populate the
~cideploy known_hosts file otherwise though....

### CODE REVIEW

**Comment by j2sol** [comment]
Here's a thing I've done at previous locations to prime the known_hosts:

```
---
- name: Load Keys
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:
    - name: simple ssh
      command: ssh -o StrictHostKeyChecking=no -F {{ ssh_config }} {{ item }} echo
      when: item != 'localhost'
      with_items: "{{ groups['all'] }}"
```

Now the bit here about using an ssh_config, that is just because we had one for this site. We don't need on here, we just have to put more options directly on the command line. This should really only be used in specific scenarios, such as booting new instances.

**Comment by SpamapS** [comment]
FYI, OpenSSH includes a command named 'ssh-keyscan' for this purpose. However, has anyone considered scraping keys from the console logs of our booted instances?

**Comment by j2sol** [comment]
Getting the host key is a interesting option, but scraping the log seems fragile.

https://review.openstack.org/#/c/167202/ could make that better, but alas...

**Comment by rattboi** [comment]
Ok, so we need something like the following:

https://raymii.org/s/tutorials/Ansible_-_create_OpenStack_servers_with_os_server.html#Instance_creation_playbook

The only open question on my end is whether os_server.results contains info for all hosts, or just newly-created ones. If it contains results for all hosts, then we're good. If not, we're still in trouble if we decide to spin up a new bastion to manage an already-created set of nodes.

**Comment by j2sol** [comment]
I might be ignorant, but where is that set of code dealing with host keys?

**Comment by rattboi** [comment]
No, you're right. I meant the technique to get the hosts involved in our dynamic inventory. For dealing with known_hosts, you can do this: http://hakunin.com/six-ansible-practices#path-to-success-1

**Comment by nibalizer** [comment]
Yah I am -1 on this because it hurts security. First time users can be expected to deal with host keys in the normal way.

**Comment by rattboi** [comment]
Looks like we aren't worried about this, and will just do it manually the first time we spin up a new cloud. I'm gonna close it.

**Pull request closed without merging**
