### PR TITLE
Fix signed-off-by-test.sh for best practices

### PR DESCRIPTION
**Pull request by mlangbehn**
Script was updated in anticipation of `shellcheck` being added to CI
tests.

Signed-off-by: Matt Langbehn <matthew.langbehn@gmail.com>

### CODE REVIEW

**Comment by eggshell** [comment]
Can we get some explanation in the commit summary? Also, we might want to get a shellcheck test in before this.

**Comment by mlangbehn** [comment]
Yes, I will update the commit message to be more clear.

We can not add `shellcheck` to this repository until this pull request merges...but I do plan on adding it. My updated commit message will say so.

**Comment by eggshell** [comment]
@mlangbehn yep, I got the order backwards. Thanks.

**Comment by mlangbehn** [comment]
Please note, the Travis CI failure is not related to this pull request:
```
[...SNIPPED...]
Get:86 http://archive.ubuntu.com/ubuntu xenial/main amd64 ssh-import-id all 5.5-0ubuntu1 [10.2 kB]
debconf: delaying package configuration, since apt-utils is not installed


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received


The build has been terminated
```

**Comment by eggshell** [comment]
@mlangbehn I tried pushing it back through. Looks like Travis is a little sluggish atm.

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/64/1484758437.88/ubuntu-hoist : FAILURE in 27s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/64/1484758437.88/ansible-syntax : SUCCESS in 54s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/64/1484758437.88/hoist-checks : SUCCESS in 7s

**Comment by eggshell** [comment]
recheck

**Review by eggshell — APPROVED** [review]
lgtm

**Pull request merged**
