### PR TITLE
Start using uwsgi 

### PR DESCRIPTION
**Pull request by jamielennox**
Uwsgi is a service runner that handles all sorts of http things as well as process reloads. It's major advantage to us is that we can run multiple independent applicatoins with different virtualenvs and link them all behind the same apache process.

### CODE REVIEW

**Comment by jamielennox** [comment]
I cannot figure out how to make this work with unix domain sockets. We meet all the version requirements but whatever i try gives some sort of error.

**Review by rattboi — COMMENTED** [review]
LGTM. :+1:

I'll let someone else approve though, just in case I missed something.

**Review by SpamapS — APPROVED** [review]

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489088510.69/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489088532.43/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489088553.35/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489088572.9/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489088654.34/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489088674.06/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489088692.95/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489088717.83/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489088739.19/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489088772.57/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by rattboi** [comment]
gate-recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489088876.55/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489088901.58/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489088925.45/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489088947.02/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089010.56/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089031.7/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089050.84/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089088.54/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089108.31/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089130.92/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089207.18/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089226.21/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089244.39/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089277.98/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089294.7/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089315.2/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089334.41/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089410.57/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089430.68/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089452.34/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089480.61/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089498.16/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089517.54/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089536.68/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089589.4/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089616.51/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089636.08/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089668.18/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089688.79/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089711.22/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089759.82/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089812.25/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089868.09/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089885.24/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089908.9/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089929.95/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089950.12/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089971.7/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489089991.87/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090078.05/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090098.78/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090118.48/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090137.77/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090155.47/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090171.88/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090188.6/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090210.29/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090302.95/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090323.74/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090342.97/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090372.26/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090393.57/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090416.73/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090489.03/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090514.39/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090541.36/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090558.84/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090576.97/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090599.89/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090616.67/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090646.82/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090665.11/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090686.49/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090752.45/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090771.99/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090791.72/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090811.7/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090878.43/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090898.03/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090917.36/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090946.14/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090966.09/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489090988.45/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489091073.71/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489091093.65/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489091121.75/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489091140.59/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489091157.52/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489091178.94/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489091198.38/bonnyci-run-gate-multinode : FAILURE in 8s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489091263.89/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489091281.38/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489091302.43/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489091321.98/bonnyci-run-gate-multinode : FAILURE in 40s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489091423.02/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489091437.51/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489091464.79/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/hoist/203/1489091490.19/bonnyci-run-gate-multinode : FAILURE in 7s

**Comment by rattboi** [comment]
gate-recheck

**Pull request merged**
